import "server-only";

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

import { downloadFileBuffer, type ExportContext } from "@/lib/exports/shared";

export async function buildPdfPacket(ctx: ExportContext): Promise<Buffer> {
  const out = await PDFDocument.create();
  const helv = await out.embedFont(StandardFonts.Helvetica);
  const helvBold = await out.embedFont(StandardFonts.HelveticaBold);

  // ---------- Cover page ----------
  const cover = out.addPage([612, 792]);
  cover.drawText("IntakeClean Document Packet", {
    x: 50,
    y: 720,
    size: 22,
    font: helvBold,
    color: rgb(0.06, 0.12, 0.24),
  });
  cover.drawText(`${ctx.organization.name}`, { x: 50, y: 690, size: 12, font: helv, color: rgb(0.4, 0.4, 0.4) });
  cover.drawText(`Matter: ${ctx.matter.matter_name}`, { x: 50, y: 660, size: 14, font: helvBold });
  cover.drawText(`Client: ${ctx.client.full_name}`, { x: 50, y: 640, size: 12, font: helv });
  cover.drawText(`Exported: ${new Date().toLocaleString()}`, { x: 50, y: 620, size: 10, font: helv });

  cover.drawText("Documents included:", { x: 50, y: 580, size: 12, font: helvBold });
  let cursor = 560;
  ctx.acceptedFiles.forEach((f, idx) => {
    cover.drawText(`${idx + 1}. ${f.detected_document_type ?? "Document"} — ${f.original_file_name}`, {
      x: 60,
      y: cursor,
      size: 10,
      font: helv,
    });
    cursor -= 16;
  });
  cover.drawText("This packet was generated by IntakeClean and reviewed by firm staff.", {
    x: 50,
    y: 80,
    size: 9,
    font: helv,
    color: rgb(0.5, 0.5, 0.5),
  });

  let groupedByType: string | null = null;

  for (const file of ctx.acceptedFiles) {
    const docType = file.detected_document_type ?? "Other";
    if (docType !== groupedByType) {
      groupedByType = docType;
      const divider = out.addPage([612, 792]);
      divider.drawText(docType, { x: 50, y: 700, size: 22, font: helvBold, color: rgb(0.06, 0.12, 0.24) });
      divider.drawLine({ start: { x: 50, y: 690 }, end: { x: 562, y: 690 }, thickness: 1, color: rgb(0.83, 0.83, 0.83) });
    }
    await embedFile(out, file, helv);
  }

  // Page numbers
  const pages = out.getPages();
  pages.forEach((p, idx) => {
    const { width } = p.getSize();
    const text = `Page ${idx + 1} of ${pages.length}`;
    const w = helv.widthOfTextAtSize(text, 9);
    p.drawText(text, { x: width - w - 30, y: 18, size: 9, font: helv, color: rgb(0.4, 0.4, 0.4) });
  });

  return Buffer.from(await out.save());
}

async function embedFile(
  doc: PDFDocument,
  file: ExportContext["acceptedFiles"][number],
  helv: import("pdf-lib").PDFFont,
) {
  const path = file.processed_storage_path ?? file.original_storage_path;
  const bucket = file.processed_storage_path ? "processed-documents" : "original-documents";
  const buffer = await downloadFileBuffer(path, bucket);
  if (!buffer) return;

  if (file.original_mime_type === "application/pdf" || file.processed_storage_path?.endsWith(".pdf")) {
    try {
      const src = await PDFDocument.load(buffer, { ignoreEncryption: true });
      const copies = await doc.copyPages(src, src.getPageIndices());
      copies.forEach((page) => doc.addPage(page));
      return;
    } catch (error) {
      console.error("[pdf-packet] could not embed pdf", { file: file.original_file_name, error });
    }
  }

  try {
    const isPng = file.processed_storage_path?.endsWith(".png") || file.original_mime_type === "image/png";
    const image = isPng ? await doc.embedPng(buffer) : await doc.embedJpg(buffer);
    const { width: imgW, height: imgH } = image.scale(1);
    const page = doc.addPage([612, 792]);
    const margin = 36;
    const maxW = 612 - margin * 2;
    const maxH = 792 - margin * 2 - 24;
    const scale = Math.min(maxW / imgW, maxH / imgH, 1);
    const drawW = imgW * scale;
    const drawH = imgH * scale;
    page.drawImage(image, {
      x: (612 - drawW) / 2,
      y: 792 - margin - drawH,
      width: drawW,
      height: drawH,
    });
    page.drawText(file.original_file_name, {
      x: margin,
      y: 24,
      size: 9,
      font: helv,
      color: rgb(0.4, 0.4, 0.4),
    });
  } catch (error) {
    console.error("[pdf-packet] could not embed image", { file: file.original_file_name, error });
  }
}
